name: Update Personal Code Stats

on:
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history
          token: ${{ secrets.PAT }}  # Use PAT for checkout

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Get personal commit stats
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          python get_commit_stats.py

      - name: Update README
        run: |
          sed -i '/<!-- CODE_CHANGES -->/c\<!-- CODE_CHANGES -->\n```\nPersonal code changes: '"$(cat commit_stats.txt)"'\n```' README.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update personal code stats" || exit 0
          git push https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git