name: 更新个人代码统计

on:
  schedule:
    - cron: '0 0 * * 0'  # 每周日午夜运行
  workflow_dispatch:  # 允许手动触发

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 获取所有历史记录
          token: ${{ secrets.PAT }}  # 使用PAT进行checkout

      - name: 设置Python环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 获取个人所有commit的统计
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          echo "GITHUB_USERNAME: $GITHUB_USERNAME"
          echo "GITHUB_TOKEN 是否设置: ${{ secrets.PAT != '' }}"
          python get_commit_stats.py
        continue-on-error: true

      - name: 检查统计结果
        id: check_stats
        run: |
          if [ -f commit_stats.txt ]; then
            echo "::set-output name=stats_exist::true"
          else
            echo "::set-output name=stats_exist::false"
          fi

      - name: 更新 README
        if: steps.check_stats.outputs.stats_exist == 'true'
        run: |
          sed -i '/<!-- CODE_CHANGES -->/c\<!-- CODE_CHANGES -->\n```\n个人代码变更: '"$(cat commit_stats.txt)"'\n```' README.md

      - name: 提交更改
        if: steps.check_stats.outputs.stats_exist == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "更新个人代码统计" || exit 0
          git push https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git